### PR TITLE
Added highlight for SQL queries

### PR DESCRIPTION
**Pull request by edgardmessias**
Added highlight for SQL queries

Light Theme:
image

Dark Theme:
image

### CODE REVIEW

**Comment by edgardmessias** [comment]
@itsgoingd , what you think about to add [@sqltools/formatter](https://www.npmjs.com/package/@sqltools/formatter)?

**Comment by itsgoingd** [comment]
Hey, PR looks cool. I will need to pull this and try it out before merging, will try to get this done before 5.0 release.

@sqltools/formatter - not sure, how would you like to use it? We already do uppercase keywords server-side. I think multi-line formatting would make it harder to find relevant queries in the database tab (too much scrolling). I feel like the highlighting might be the better idea.

**Comment by edgardmessias** [comment]
Thanks @itsgoingd 

My fear is about long queries horizontally.

Maybe we can use an option to show only a few lines and a button to "show more".

**Comment by itsgoingd** [comment]
I wouldn't be against implementing this as a toggle on the queries table. Eg. the timeline has a toggle to always show event details. In a similar fashion we could have a toolbar item on the queries table itself that would enable formatting queries when active.

**Comment by edgardmessias** [comment]
@itsgoingd , great suggestion and I already updated with this change

**Comment by edgardmessias** [comment]
ping @itsgoingd

**Comment by itsgoingd** [comment]
Hey, sorry for the delay, I'm pretty busy atm. I've played with this a bit and it looks pretty cool. Didn't want to make big changes or delay the 5.0 release though. So I've decoded to keep this for 5.1, will merge into master soon to iterate on it a bit more.

**Comment by itsgoingd** [comment]
Merging to master now for the next release cycle, thanks!

**Pull request merged**
