### PR TITLE
Added new "models" tab

### PR DESCRIPTION
**Pull request by itsgoingd**
- added new "models" tab including
    - total counts of retrieved, created, updated and deleted models
    - individual model actions with support for showing attributes of retrieved models and changes of created and updated models
    - per-model counts of retrieved, created, updated and deleted instances
- https://github.com/itsgoingd/clockwork/pull/397

Screenshot 2020-05-18 at 00 46 05

Screenshot 2020-05-18 at 00 54 56

## todo

- consider adding an option to show models stats in performance tab
- should we show model actions on timeline?

### CODE REVIEW

**Comment by mstaack** [comment]
briliant! ❤️

**Comment by llaville** [comment]
@itsgoingd Just to let you know, that I love this project (https://github.com/DamienHarper/DoctrineAuditBundle) Symfony Bundle, to audit Doctrine Entities 
And its demo offline, but with some screenshots as preview: https://github.com/DamienHarper/doctrine-audit-bundle-demo

Perharps it will give you some new ideas !

**Comment by reinink** [comment]
This is awesome! I added something very similar to the Laravel Debugbar ([see here](https://github.com/barryvdh/laravel-debugbar/pull/947)).

**Comment by itsgoingd** [comment]
thanks! i've seen the pr when doing research for this feature, definitively an important metric to have.

**Comment by pawelmysior** [comment]
This is great stuff!

**Pull request merged**
