### PR TITLE
Use v-if instead of v-show to minimize DOM interaction

### PR DESCRIPTION
**Pull request by eigan**
Using v-show is almost never necessary and will cause a lot of uneeded DOM changes. This is especially noticeable when switching between requests, which for me always ended up with "Out of memory" issue. 

Now, switching between requests is a lot faster _(unless you are on a tab which uses `<popover>` on every row (I am going to fix those next)._

_EDIT: Still have out of memory issues. Will need to investigate some more._
_EDIT2: The issue with of memory have been resolved. Unrelated. Just logged to much data on events.__

### CODE REVIEW

**Comment by eigan** [comment]
@itsgoingd Let me know if you need me to do anything to get this through. These two PR really speeds up the UI for me :)

**Comment by itsgoingd** [comment]
Hey, thanks for the PR! Nothing wrong with it, I just haven't been able to properly test it yet.

For some context, using v-show was completely intentional. The idea was to make switching between tabs as fast as possible when you have a request already selected since they are already rendered. But I definitively can see how not doing so might make the app more responsive overall, just need to actually benchmark it.

**Comment by eigan** [comment]
@itsgoingd Let me know if you feel it is any slower. In my tests was it _a lot_ faster :)

**Comment by eigan** [comment]
> Generally speaking, v-if has higher toggle costs while v-show has higher initial render costs. So prefer v-show if you need to toggle something **very often**, and prefer v-if if the condition is unlikely to change at runtime.

_(emphasis mine)_

https://vuejs.org/guide/essentials/conditional.html#v-if-vs-v-show

I wanted to introduce clockwork to our stack (SPA with many http-requests), but it was annoyingly slow and consumed a lot of memory. Sad that this was never addressed.

**Comment by itsgoingd** [comment]
Hey, this will be addressed in the next major release, along with other stuff. Unfortunately I have no plans on doing another 5.x release at the moment.

**Pull request closed without merging**
