### PR TITLE
Use size accessor property of javascript Sets

### LINKED ISSUE #14: Query table not showing Connection column when there are multiple connections
When there are queries that are using different connection sources, the "Connection" column is not being added.

In my case, I have a page with queries that are going to a MySQL database and an MSSQL database. The Connection is not displayed.

I believe this logic is trying to determine if there are multiple connections:

https://github.com/underground-works/clockwork-app/blob/ebe6296fec140c328fbf29b058e3c92f6598b012/src/components/Tabs/DatabaseTab.vue#L81-L89

### PR DESCRIPTION
**Pull request by fitztrev**
Fixes #14 

Javascript Sets use `size` to get the number of elements.

```javascript
(new Set).length
// => undefined
(new Set).size
// => 0
```

### CODE REVIEW

**Comment by itsgoingd** [comment]
Thanks! I'll tag a new release in a day or two.

**Comment by fitztrev** [comment]
@itsgoingd Looks like 4.0.3 is tagged but not pushed to the Chrome extension store ([still showing 4.0.2](https://chrome.google.com/webstore/detail/clockwork/dmggabnehkmmfmdffgajcflpdjlnoemp)).

**Comment by itsgoingd** [comment]
I guess I forgot to publish the new version, should be fixed shortly. Thanks for letting me know.

**Comment by fitztrev** [comment]
@itsgoingd Thanks!

**Pull request merged**
